// <auto-generated />
namespace NieGumex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nowa06 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nowa06));
        
        string IMigrationMetadata.Id
        {
            get { return "201605031850553_nowa06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
