// <auto-generated />
namespace NieGumex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class factures_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(factures_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201604142235044_factures_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
